services:
  gilfi-app:
    build: .
    container_name: gilfi_container
    environment:
      - DISPLAY=${DISPLAY}
      # Prevents shared memory errors with X11 in some Linux distros
      - QT_X11_NO_MITSHM=1
    volumes:
      # Mounting the data directory
      - ./data:/app/data:Z
      # Mounting src for interactive dev and backend-as-a-package
      - ./src:/app/src:Z
      # X11 Socket
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    # Necessary for rootless Podman to access the host display
    network_mode: "host"
    stdin_open: true
    tty: true
    # Maps your host user to the container user to avoid permission issues with the .db file
    userns_mode: "keep-id"